name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run build

  build_docsite:
    name: Build documentation site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run docs

  test_style:
    name: Test code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run style

  test_node:
    name: Test Node.js @${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  test_typescript:
    name: Test TypeScript @${{ matrix.ts-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ts-version:
          - ~4.7
          - ~4.8
          - ~4.9
          - ~5.0
          - ~5.1
          - next
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm i -D typescript@${{ matrix.ts-version }}
      - run: npm run typecheck
